AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  VerificationToken:
    Description: Verification token from Slack app settings
    Type: String
    NoEcho: true
  AccessToken:
    Description: OAuth access token from Slack app settings
    Type: String
    NoEcho: true
Resources:
  MACDetectorAPI:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '2017-06-11T02:20:25Z'
          title:
            Ref: AWS::StackName
        basePath: /Prod
        schemes:
        - https
        paths:
          /:
            post:
              produces:
              - application/json
              responses:
                '200':
                  description: 200 response
                  schema:
                    $ref: '#/definitions/Empty'
              x-amazon-apigateway-integration:
                responses:
                  default:
                    statusCode: '200'
                uri:
                  Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MACDetectorFunction.Arn}/invocations
                passthroughBehavior: when_no_match
                httpMethod: POST
                contentHandling: CONVERT_TO_TEXT
                type: aws
        definitions:
          Empty:
            type: object
            title: Empty Schema
  MACDetectorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: Checks Slack message.channels events for images. If an image is
        found uses Rekognition to extract the MAC Address.
      Handler: find_mac.lambda_handler
      Runtime: python3.6
      Timeout: 10
      CodeUri: s3://patrick-demo-bucket/cd6e6be4602b831b92dce1eb37d833a4
      Environment:
        Variables:
          VERIFICATION_TOKEN:
            Ref: VerificationToken
          ACCESS_TOKEN:
            Ref: AccessToken
      Events:
        MACDetectorAPIPost:
          Type: Api
          Properties:
            Path: /
            Method: post
            RestApiId:
              Ref: MACDetectorAPI
      Policies:
      - RekognitionLabelsPolicy: {}
Outputs:
  RequestURL:
    Description: Prod URL for API to use as Request URL for Slack app
    Value:
      Fn::Sub: https://${MACDetectorAPI}.execute-api.${AWS::Region}.amazonaws.com/Prod/
